AWSTemplateFormatVersion: "2010-09-09"
Description: Core services for CLI Tool

Resources:

  LambdaSourceBucket:
    Type: AWS::S3::Bucket

  LeaderboardTable: 
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: LeaderboardTable
        AttributeDefinitions: 
          - 
            AttributeName: "Track"
            AttributeType: "S"
          - 
            AttributeName: "Person"
            AttributeType: "S"
        KeySchema: 
          - 
            AttributeName: "Track"
            KeyType: "HASH"
          - 
            AttributeName: "Person"
            KeyType: "RANGE"
        ProvisionedThroughput: 
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

Outputs:

  LambdaBucketName:
    Description: Name of S3 Bucket for Lambda Source
    Value: !Ref LambdaSourceBucket

  DynamoTableName:
    Description: Name of DynamoDB table name
    Value: !Ref LeaderboardTable