---
SAGEMAKER_SHARED_S3_PREFIX: "data-0f74113c-c149-48cb-ac45-d06480d4d161/models/rightangle/sagemaker-robomaker-artifacts"
UPPER_LANE_CHANGE_TIME: "5.0"
CAR_NAME: "SteveDR01"
KINESIS_VIDEO_STREAM_NAME: "dr-kvs-372026249783-20201025145529-b57d1443-84af-44f7-8942-56e82c07c052"
TRAINING_JOB_ARN: "arn:aws:deepracer:us-east-1:606363841935:training_job/DFdXULtfQOGKDSAucFGHxQ"
BOT_CAR_SPEED: "2.0"
REWARD_FILE_S3_KEY: "data-0f74113c-c149-48cb-ac45-d06480d4d161/models/rightangle/reward_function.py"
MP4_S3_OBJECT_PREFIX: "data-0f74113c-c149-48cb-ac45-d06480d4d161/models/rightangle/videos/training/training-20201025145530-DFdXULtfQOGKDSAucFGHxQ"
WORLD_NAME: "Aragon"
SAGEMAKER_SHARED_S3_BUCKET: "aws-deepracer-data-us-east-1-1"
RACE_TYPE: "HEAD_TO_HEAD_RACING"
MODEL_METADATA_FILE_S3_KEY: "data-0f74113c-c149-48cb-ac45-d06480d4d161/models/rightangle/model_metadata.json"
IS_LANE_CHANGE: "true"
BODY_SHELL_TYPE: "deepracer"
TARGET_REWARD_SCORE: "None"
CHANGE_START_POSITION: "true"
METRICS_S3_OBJECT_KEY: "data-0f74113c-c149-48cb-ac45-d06480d4d161/models/rightangle/metrics/training/training-20201025145530-DFdXULtfQOGKDSAucFGHxQ.json"
AWS_REGION: "us-east-1"
LOWER_LANE_CHANGE_TIME: "1.0"
NUMBER_OF_EPISODES: "0"
NUMBER_OF_BOT_CARS: "1"
S3_KMS_CMK_ARN: "arn:aws:kms:us-east-1:372026249783:key/09efde8f-fe33-4b7a-b88f-2f62aa2706a8"
METRIC_NAMESPACE: "AWSDeepRacer"
ALTERNATE_DRIVING_DIRECTION: "false"
ROBOMAKER_SIMULATION_JOB_ACCOUNT_ID: "372026249783"
SIMTRACE_S3_BUCKET: "aws-deepracer-data-us-east-1-1"
METRICS_S3_BUCKET: "aws-deepracer-data-us-east-1-1"
MP4_S3_BUCKET: "aws-deepracer-data-us-east-1-1"
SIMTRACE_S3_PREFIX: "data-0f74113c-c149-48cb-ac45-d06480d4d161/models/rightangle/sim-trace/training"
JOB_TYPE: "TRAINING"
METRIC_NAME: "TrainingRewardScore"
CAR_COLOR: "Black"
